[package]
name = "assert-keys-equal-macro"
version = "0.1.0"
authors = ["hunter Jozwiak <hunter.t.joz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.77", features = ["full"] }
proc-macro2 = "1.0.29"
solana-program = "1.7.13"
bs58 = "0.4.0"
quote = "1.0.9"
trybuild = "1.0.52"
[lib]
proc-macro = true
