[package]
name = "assert-keys-equal-macro"
version = "0.1.0"
authors = ["hunter Jozwiak <hunter.t.joz@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.96", features = ["full"] }
solana-program = "1.11.0"
proc-macro2 = "1.0.39"
bs58 = "0.4.0"
quote = "1.0.18"
trybuild = "1.0.63"
[lib]
proc-macro = true
